volumes:
  todo_myslq: {}

services:
  mysql:
    container_name: todo-server-mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - todo_myslq:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    restart: always
